### ISSUE TITLE
./lsup-admin bootstrap fails

### ISSUE THREAD

**Issue by jamesmooneybodleian** [scossu/lakesuperior#10]
Following README.MD instructions at line 7, when running the command:

./lsup-admin bootstrap

Fails with the following error for me

Reading configuration at /root/lake/lakesuperior/etc.defaults
Traceback (most recent call last):
  File "./lsup-admin", line 7, in <module>
    import lakesuperior.env_setup
  File "/root/lake/lakesuperior/lakesuperior/env_setup.py", line 2, in <module>
    from lakesuperior.globals import AppGlobals
  File "/root/lake/lakesuperior/lakesuperior/globals.py", line 6, in <module>
    from lakesuperior.dictionaries.namespaces import ns_collection as nsc
ImportError: No module named dictionaries.namespaces

**Comment by scossu** [comment]
@jamesmooneybodleian I am trying to reproduce this. Which branch and commit are you using?

It sems like your installation root is on `root/lake/lakesuperior`, correct? Are you running in a virtualenv?

**Comment by scossu** [comment]
Also, which OS and Python version are you using?

**Comment by jamesmooneybodleian** [comment]
Running a VirtualBox of Ubuntu 16.04 LTS with python 2.4.14. Cloned master branch and running commands in virtualenv.

Hope that helps.

**Comment by scossu** [comment]
LAKEsuperior supports Pyhon 3.5 or later. You should check if you have that installed in your VM already, and when you create your virtualenv, specify the Python executable with the `-p` option.

**Comment by jamesmooneybodleian** [comment]
Ah ok. My bad. Will re do and report back if there are any issues.
