### ISSUE TITLE
Minor correction to README.md? Maybe?

### ISSUE THREAD

**Issue by jamesmooneybodleian** [scossu/lakesuperior#11]
For line 6:
Install dependencies: pip install -r requirements.txt

should it be?
Install dependencies: pip3 install -r requirements.txt

**Comment by scossu** [comment]
If python 3.x is in your PATH, `pip` should point to the 3.x version. Is this not happening for you while you are in the virtualenv? What is the output of `which pip` for you?

**Comment by jamesmooneybodleian** [comment]
Strange, which pip reports /root/lake/bin/pip so from within the virtualenv and pip --version reports pip 9.0.1 from /root/lake/lib/python3.6/site-packages (python 3.6)

But when I tried to build the requirements it failed. Using pip3 it works. Odd?

**Comment by scossu** [comment]
Odd indeed, I never encountered this scenario before. And you are on an Ubuntu LTS host?

What kind of error do you get with the `pip install -r requirements.txt` command?

**Comment by scossu** [comment]
@jamesmooneybodleian I believe this is a more universal method (also uses a standard library tool which I always prefer):

    python3 -m venv <virtualenv folder>

I updated the README: https://github.com/scossu/lakesuperior/blob/master/README.md#installation-steps

Can you  please verify that this works for you on a blank slate scenario?

**Comment by scossu** [comment]
This should be fixed now.
