### ISSUE TITLE
Set up automated Docker build

### ISSUE THREAD

**Issue by mbklein** [scossu/lakesuperior#16]
@scossu: If you follow the steps to [configure an automated build](https://docs.docker.com/docker-hub/builds/) on Docker Hub, I will submit another PR to make the Quick Start even quicker. (quickerer?)

**Comment by mbklein** [comment]
If you prefer, I'm happy to set up the automated build under my Docker account (or create a lakesuperior org under Docker to do so), but I _think_ doing so requires admin access to this repo to set up the webhook that triggers the build.

**Comment by scossu** [comment]
I have set up the Docker Hub account. There are two builds (currently on their way), the "stable" one for the master branch and the "development" for the development branch. Let me know if this is good to close or if more steps are needed.

**Comment by scossu** [comment]
https://hub.docker.com/r/scossu/lakesuperior/builds/
