### ISSUE TITLE
Support PATCH on the root resource

### ISSUE THREAD

**Issue by acoburn** [scossu/lakesuperior#44]
### Environment

Operating system: OS X

Python version: 3.6.4

LAKEsuperior release, branch, or commit #: 1.0.0-alpha12 from pypi

### Steps to reproduce

1. Start lakesuperior
2. PATCH to the root container

```sh
curl -XPATCH -i localhost:8000/ldp/ -H"Content-Type: application/sparql-update" --data-binary @sparql.txt
```

(The same sparql update applied to a non-root resource succeeds)

```sparql
INSERT {
    <> <http://purl.org/dc/terms/subject> [
       a <http://example.org/Subject> ;
       <http://www.w3.org/2000/01/rdf-schema#label> "A subject" ]
} WHERE {}
```

### Observed behavior

Response:

```http
HTTP/1.1 405 METHOD NOT ALLOWED
Server: gunicorn/19.7.1
Date: Mon, 09 Apr 2018 18:51:11 GMT
Connection: keep-alive
Content-Type: text/html
Allow: HEAD, POST, GET, OPTIONS
Content-Length: 178
```

### Expected behavior

A successful response (e.g. 200 or 204)

### Other notes worth mentioning

I notice that PATCH is not included in the `Allow` header, but the root resource also advertises the `Allow-Patch` header, so it's a little inconsistent.

**Comment by scossu** [comment]
Fixed in #50
