### ISSUE TITLE
Support content negotiation

### ISSUE THREAD

**Issue by acoburn** [scossu/lakesuperior#46]
### Environment

Operating system: OS X

Python version: 3.6

LAKEsuperior release, branch, or commit #: 1.0.0-alpha12 from pypi

### Steps to reproduce

```sh
curl -i <any resource> -H"Accept: application/ld+json"
```

### Observed behavior

The response is Turtle

### Expected behavior

The response should be JSON-LD

### Other notes worth mentioning

LDP requires that servers support JSON-LD serializations (I personally see no reason to support RDF+XML). And if you are already supporting Turtle, N-Triples tends also to be really easy to support.

**Comment by scossu** [comment]
This will be resolved with #24 .

**Comment by scossu** [comment]
Fixed in c64eb391e5f1bb95930b24bb9334c61a63be05ae
