### ISSUE TITLE
Link header with anchor parameter

### ISSUE THREAD

**Issue by acoburn** [scossu/lakesuperior#48]
### Environment

Operating system: OS X

Python version: 3.6

LAKEsuperior release, branch, or commit #: 1.0.0alpha12 from pypi

### Steps to reproduce

Create an LDP-NR as with #47 

### Observed behavior

The response includes a response header such as:

```http
Link: <http://localhost:8000/ldp/ee7d7990-24d5-41d3-bc3b-0a59cfd2b739/fcr:metadata>; rel="describedby"; anchor="<http://localhost:8000/ldp/ee7d7990-24d5-41d3-bc3b-0a59cfd2b739>"
```

### Expected behavior

I would not expect to see the `anchor` parameter to be enclosed in `<>` characters.

That is, I would expect:

```http
Link: <http://localhost:8000/ldp/ee7d7990-24d5-41d3-bc3b-0a59cfd2b739/fcr:metadata>; rel="describedby"; anchor="http://localhost:8000/ldp/ee7d7990-24d5-41d3-bc3b-0a59cfd2b739"
```

### Other notes worth mentioning

https://tools.ietf.org/html/rfc8288 -- this is the specification for web linking (which defines the anchor param)
The ABNF for the anchor param is "URI Reference", as defined by https://tools.ietf.org/html/rfc3986#section-4.1

**Comment by scossu** [comment]
Fixed in #51
