### ISSUE TITLE
If-None-Match header support (R+W)

### ISSUE THREAD

**Issue by scossu** [scossu/lakesuperior#75]
Support `If-None-Match` HTTP header for GET/HEAD and PUT, as per [RFC 7232, section 3.2](https://tools.ietf.org/html/rfc7232#section-3.2).

With GET requests, the server will return a `304 Not Modified` if the resource ETag corresponds to any the client-provided ETags. 

With PUT requests, the server will return a  `412 Precondition Failed` and the resource will not be updated if a match is found. This can be used in combination with the special `*` value to prevent an update of a location that contains an existing resource.

**Comment by acoburn** [comment]
For non-safe methods such as PUT, I believe the correct response would be 412 Precondition Failed. The 304 response is for GET and HEAD.

**Comment by scossu** [comment]
@acoburn you stand correct. I updated the description.

**Comment by scossu** [comment]
Fixed in PR #82.
