### ISSUE TITLE
Spec 3.2.1: `PreferInboundReferences` pref header

### ISSUE THREAD

**Issue by scossu** [scossu/lakesuperior#96]
Change `include` value of `Prefer` header from `http://fedora.info/definitions/v4/repository#InboundReferences` to `http://fedora.info/definitions/fcrepo#PreferInboundReferences`.

See https://fedora.info/2018/11/22/spec/#additional-prefer-values , first bullet

**Comment by whikloj** [comment]
Hey @scossu I was going to try working on some of these low hanging issues. But I'm not a big Python user and I can't even figure out how you would debug this application? If you have any suggestions I'll take it, I normally use PyCharm as an IDE.

**Comment by scossu** [comment]
Oh, I wish I had known it—I got stuck on the bus with no WiFi this morning and I just almost resolved this in the meantime. It could have been a good starter. Thanks for offering!

I think most of the "compliance"-tagged tickets are relatively low-hanging and affect a shallow stack. 

I use pdb to debug all my code. When I open a PR for this (probably later this evening) you can look at the diffs. I'm glad to walk you through the code some time.
